### ISSUE TITLE
Can't post messages containing only emojis

### ISSUE THREAD

**Issue by danny-andrews** [gnprwx/nullmb#1]
I tried to make a post with the message "🐸🐸🐸" and nothing rendered to the screen. It looks like it returns a 500 in that case. It seems to work when there are characters interspersed with emojis, but fails when the message contains only emojis.

**Comment by gnprwx** [comment]
Thank you for reaching out, @danny-andrews. We can't have that kind of problem around here. I'll look into this!

**Comment by danny-andrews** [comment]
I saw your post on LinkedIn and started goofing around with it again. Dug into it a little and it looks like the badwords library freaks out if there are no alphanumeric characters. Do with this ticket what you will and have a good week. 😄😎

**Comment by gnprwx** [comment]
I see. Looks like I will fix this with my own filter of words then. Bad words is a bit over-zealous anyway! Will report back when it's fixed. Thanks again for looking into this, @danny-andrews.

**Comment by gnprwx** [comment]
Replaced bad-words with bad-words-next. This allows for emoji-only input as well as the same word filtering capabilities.  Interestingly enough, this required me to update Render's node version due to an import statement requiring node version 17 or higher, so it has been set to LTS. The site now functions as it should.
